#!/bin/bash
NAME=my-project
DIR=/home/fastapi-user/my_fastapi_project
USER=fastapi-user
GROUP=fastapi-user
WORKERS=4
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/.venv/bin/activate
BIND=127.0.0.1:8000
LOG_LEVEL=debug
LOG_FILE=/home/fastapi-user/my_fastapi_project/logs/my_fastapi_project.log

cd $DIR
source $VENV
exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=$LOG_FILE
